-- MySQL Script generated by MySQL Workbench
-- Mon Oct 18 17:01:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema personal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `personal` ;

-- -----------------------------------------------------
-- Schema personal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `personal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `personal` ;

-- -----------------------------------------------------
-- Table `personal`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `personal`.`empleados` ;

CREATE TABLE IF NOT EXISTS `personal`.`empleados` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `correo` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_hora` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_de_ingreso` VARCHAR(255) NULL DEFAULT NULL,
  `identificacion` VARCHAR(255) NULL DEFAULT NULL,
  `numero_identi` VARCHAR(255) NULL DEFAULT NULL,
  `pais_empleo` VARCHAR(255) NULL DEFAULT NULL,
  `primer_apellido` VARCHAR(255) NULL DEFAULT NULL,
  `primero_nombre` VARCHAR(255) NULL DEFAULT NULL,
  `segundo_apellido` VARCHAR(255) NULL DEFAULT NULL,
  `segundo_nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
